### PR TITLE
Compatibility with Omnipay 3.0

### PR DESCRIPTION
**Pull request by chrisvidal**

### CODE REVIEW

**Comment by leith** [comment]
I don't mind having a Omnipay 3.x version of the library (have always planned to do this), although I suspect there will be quite a few more changes than adding the implements interface call currently there. 😅

**Comment by chrisvidal** [comment]
so far so good, it works like this with Omnipay 3, both `process` and `completePurchase` looks ok;
other things to do are to update the `package.json` and the `travis.yaml` I guess

**Comment by leith** [comment]
I'll probably be making a pretty concerted effort in the next couple of weeks for making a v3 branch, as after looking at the upgrade guide, there are a few more quirks here and there to take care of and it looks like I'll need to migrate for work anyway. 😄

**Comment by leith** [comment]
@chrisvidal there were a few other changes that were needed, but have released a v3 version of this driver today. Initial tests for me for other work are all up-to-date. Do you want to run some tests on that version?

**Comment by chrisvidal** [comment]
@leith thanks for that; yes I will do some test on my current project using this new version. Will let you know, thanks

**Pull request closed without merging**
